site_dir: '../docs'
docs_dir: 'src'
site_name: John's Cloud
#site_description: 
site_author: John
#theme: readthedocs
google_analytics: ['UA-92780605-1', 'john-cd.com']
repo_url: https://github.com/john-cd/johnscloud

pages:
- Home: 'index.md'
- 'Docker Templates':
    - 'MongoDB on Docker': 'docker/mongoDB_docker.md'
    - 'ElasticSearch on Docker': 'docker/elasticsearch_docker.md'

#- User Guide:
#    - 'Writing your docs': 'user-guide/writing-your-docs.md'
#    - 'Styling your docs': 'user-guide/styling-your-docs.md'
#- About:
#    - 'License': 'about/license.md'
#    - 'Release Notes': 'about/release-notes.md'

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - wikilinks